export const stringsEN = () => {
  return {
    this_is_demo: 'This is just a demo app',
    login: 'log in',
    forgot_password: 'Forgot Password',
    password: 'Password',
    recover_password: 'Recover password',
    forgot_your_password: 'Forgot your password?',
    forgot_password_big_text:
      'Enter your email address and we will send you instructions on how to recover your password',
    email_sent: 'E-mail sent',
    enter_the_code_we_sent: "Enter the code we've sent you to ",
    to_recover_your_password: ' to recover your password',
    enter_code: 'Enter code',
    new_password: 'New password',
    enter_new_password: 'Enter your new password',
    save_and_login: 'Save and log in',
    are_you_sure_to_reset_password:
      'Are you sure you want to interrupt\nthe password recovery process? Stopping\nhere your password will not be reset.',
    interrupt: 'Cancel',
    go_back: 'Go back',
    profile: 'Profile',
    full_name: 'Full name',
    change_password: 'Change Password',
    logout: 'Log Out',
    inventory: 'Inventory',
    inventories: 'Inventories',
    add_item: 'Add item',
    change_password_title: 'Change password',
    current: 'Current',
    new: 'New',
    enter_your_current_password: 'Enter your current password',
    enter_your_new_password: 'Enter your new password',
    save: 'Save',
    save_the_changes: 'Save the changes?',
    yes_save: 'Yes, save',
    no_discard: 'No, discard',
    inventory_title: 'Inventory',
    your_inventory_is_empty: 'Your inventory is empty',
    enter_product_name_to_search: 'Enter item name to search',
    add_manually: 'Add manually',
    enter_product_name: 'Enter item name',
    save_Button: 'Save',
    done: 'Done',
    quantity: 'Quantity',
    supplier: 'Supplier',
    group: 'Group',
    select_product_group: 'Select item group',
    enter_quantity_in_kg: 'Enter quantity in kg',
    enter_quantity: 'Enter quantity',
    item_has_been_added_to_inventory: 'Item has been added to inventory',
    number_of_cartons_in_a_pallet: 'Number of cartons in a pallet',
    number_of_piece_in_a_carton: 'Number of piece in a carton',
    crt_in_pall: 'crt in pall',
    pcs_in_crt: 'pcs in crt',
    enter: 'Enter',
    pcs: 'Pcs',
    crt: 'Crt',
    pall: 'Pall',
    expires_on: 'Expires on',
    select_expiration_date: 'Select expiration date',
    select_product_group_title: 'Select item group',
    gtin_type: 'Gtin type',
    add_Weighed: 'Add Weighed',
    scan_barcode: 'Scan Barcode',
    change: 'Change',
    please_fill_in_all_obligatory_fields:
      'Please fill in all obligatory fields',
    enter_supplier_name: 'Enter supplier name',
    select_supplier: 'Select supplier',
    edit_Item: 'Edit Item',
    scan_barcode_to_search: 'Scan barcode to search',
    save_Changes: 'Save Changes',
    item_not_in_stock: 'The items is not in the inventory',
    do_you_want_to_delete: 'Do you want to delete',
    from_the_warehouse: 'from the inventory?',
    the_item_has_been_added_to_the_stock: 'The item is added to inventory',
    please_select_Vendor: 'Please select supplier',
    item_group_name_and_group_code: 'Item group name and group code',
    cancel: 'Cancel',
    kart_per_pallet_should_not_be_zero: 'krt per pallet can not be zero',
    pcs_per_kart_should_not_be_zero: 'stk per krt can not be zero',
    quantity_should_not_be_zero: 'Quantity can not be zero',
    pcs_carts_palls_should_not_be_null: 'stk/krt or krt/pall can not be zero',
    pcs_kart_should_not_be_null: 'stk/krt can not be zero',
    continue_editing: 'Keep editing',
    do_you_want_to_delete_this_entry: 'Do you want to delete this entry',
    you_are_not_allowed_to_enter_the_special_characters:
      'You are not allowed to enter the special characters',
    add_to_stock: 'Add to inventory',
    add_products: 'Add more items',
    your_password_has_been_changed: 'Your password has been changed',
    click_on_recover_password_below:
      'Click on "Recover password" and we will send you an e-mail to',
    with_instructions_on_how_to_recover_your_password:
      'with instructions on how to recover your password ',
    yes_delete: 'delete',
    move_on: 'Continue',
    localeDate: 'en-au',
    localPath: 'moment/locale/en-au',
    cancel_process: 'Cancel check-in process for',
    if_you_cancel:
      "If you cancel the check-in for this item, the quanity of this item in your inventory won't be updated.",
    cancel_checkin: 'cancel check-in',

    cancel_checkout_process: 'Cancel check-out process for',
    if_you_cancel_checkout:
      "If you cancel the check-out for this item, the quanity of this item in your inventory won't be updated.",
    cancel_checkout: 'cancel check-out',

    enter_email_address: 'Enter e-mail address',
    enter_password: 'Enter password',
    check_in_delivered_products: 'Check in delivered items',
    search_product_to_check_in: 'Search a item to check in',
    barcode: 'strekkode',
    barcode_type: 'Barcode type',
    what_type_of_barcode_did_you_scan: 'What type of barcode did you scan? ',
    f_pack: 'F-pack',
    d_pack: 'D-pack',
    t_pack: 'T-pack',
    tips_text:
      'Tip: Include a measurement unit in the item name (e.g. Coriander, bundle or Draft beer, keg 30 l). This helps you easier distinguish items when searching or browsing the inventory.',
    check_out_of_inventory: 'Check out of inventory',
    please_select_product_batch_first: 'Please select item batch first',
    we_have_only: 'We have only ',
    available: ' available',
    how_many_would_you_like_to_check_out:
      'How many would you like to check out?',
    select_product_batch: 'Select item batch',
    expiration_date_not_available: 'Expiration date not available',
    quantity_to_check_out: 'Quantity to check out',
    has_been_deleted_from_inventory: 'has been deleted from inventory',
    days_left: ' Days Left',
    the_change_has_been_saved: 'The change has been saved',
    check_in_to_inventory: 'Check in to inventory',
    add_product_manually: 'Add item manually',
    this_product_is_not_in_your_inventory:
      'This item is not\nin your inventory',
    this_product_is_not_in_the_database: 'This item is not\nin the database',
    search_product_to_check_out: 'Search a item to check out',
    expiring_on: ' expiring on ',
    have_been_checked_out_of_inventory: ' have been checked out of inventory ',
    //New
    personal_details: 'Personal Details',
    weekly_reports: 'Weekly Reports',
    see_All: 'See All',

    nothing_exp_soon: 'Nothing Expires\nSoon. Good job!',
    see_detail: 'See Detail',
    expiration_date_not_specified: 'Expiration date not specified',
    ordered: 'ordered',
    accepted: 'accepted',
    today: 'Today',
    today_text: 'today ',
    tomorrow: 'Tomorrow ',
    tomorrow_text: 'tomorrow ',
    had_issue: 'had issue',
    scheduled: 'scheduled',
    delivered: 'delivered',

    the_product_youre_looking:
      "The item you're looking for was not found in this order",
    finish_and_update_inventory: 'Finish & update inventory',
    checked: 'checked',
    left: 'left',
    add_a_note: 'Add a note',
    note: 'note',
    quality: 'quality',
    is_there_anything_wrong: 'Is there anything wrong?',
    add_expiration_date: 'Add an expiration date',
    expiration_date: 'expiration date',
    accepting: 'accepting',
    delivery: 'Delivery',
    add: 'Add',

    pick_Order_long_text:
      'Pick an order from the list below to start \nchecking off delivered items. If you don’t see \nyour order in the list, take a picture of the \ndelivery note to upload it to the app.',
    // "Pick a scheduled order from the list below to start checking off delivered items. If you don't see an order in the list, please contact your manager to upload the order via the web administration.",
    you_have_no_delivered_orders: 'You have no delivered orders',
    you_have_no_scheduled_orders: 'You have no scheduled orders',
    your_Inventory_has_been_updated: 'Your Inventory has been updated.',
    specify_expiration_date: 'Specify expiration date',
    specify_quantity: 'Specify quantity',

    add_another_expiration_date: 'Add another expiration date',
    show_100_items: 'Show Items',
    clear_all: 'Clear All',
    availability: 'Availability',
    in_Stock: 'In stock',
    out_of_Stock: 'Out of stock',
    search_inventory: 'Search Inventory',
    your_changes_have_been_saved: 'Your changes have been saved',
    sort: 'sort',
    filter: 'filter',
    // add: "add",
    please_fill_product_name_field: 'Please fill item name field',
    add_new_product_to_inventory: 'Add new item\nto inventory',
    product_name: 'item name',
    continue: 'continue',
    exp_Not_specified: 'Exp: Not specified',
    day_left: 'Day Left',
    expired: 'Expired',
    edit: 'Edit',
    expires_not_specified: 'Expires not specified',
    expires: 'Expires',
    total_quantity: 'Total Quantity',
    no_Items_Found: 'No Items Found',
    please_check_your_typos:
      'Please check your typos or add this item\nto your inventory first.',
    add_new_item: 'add new item',
    select_purchase_unit: 'Select purchase unit...',
    one_purchase_unit: '1 PURCHASE UNIT =',
    select_stocktaking_unit: 'Select stocktaking unit...',
    setup_unit_conversions: 'Setup unit\nconversions',
    purchase_unit: 'Purchase Unit',
    stocktaking_unit: 'Stocktaking Unit',
    how_do_you_measure_or_count:
      'How do you measure or count this item when\nyou check your inventory?',
    specify_conversion: 'Specify conversion',
    select_measurement_unit: 'Select measurement unit',
    basic_measurement_unit: 'Basic measurement unit',
    measurement_unit: 'Measurement Unit',
    how_many_basic_measurement:
      'How many basic measurement units are there in\none stocktaking unit?',
    first_to_Expire: 'First to Expire',
    last_to_Expire: 'Last to Expire',
    recently_Updated: 'Recently Updated',
    alphabet_A_Z: 'Alphabet (A-Z)',

    save_product: 'save item',

    items_will_expire_soon: ' items will expire soon',
    log_in_to_Demo: 'Log in\nto Demo App',
    name: 'Name',
    first_name_Last_name: 'First name Last name',
    company_name: 'Company name',

    email: 'email',
    your_Password: 'Your Password',
    eight_Characters: '8 Characters',
    forgotten_password: 'Forgotten password?',
    example_example_com: 'example@example.com',

    check_your_inbox: 'Check your inbox',
    go_to_my_inbox: 'go to my inbox',

    reset_Password: 'Reset Password',
    search_items: 'Search Items',

    pick_an_item_to_check_out: 'Pick an item to\ncheck out',

    not_Defined: 'Not Defined',
    please_select_expiration_date_first: 'Please select expiration date first',
    Please_select_expiration_date_and_enter_quantity:
      'Please select expiration date and enter quantity',

    please_select_expiration_date: 'Please select expiration date ',
    please_enter_quantity: 'Please enter quantity',

    check_out: 'Check out',

    we_haven_found_any_items_your:
      "We haven't found any items in your\ninventorythat would match your search.",

    search_results: 'Search Results',
    E_mail: 'E-mail',
    sign_up: 'Sign up',
    stop_food_waste: 'Stop Food Waste',
    welcome_message:
      'Gain control over your food inventory\nusing our food inventory management\nsolutions.',
    has_been_deleted_from_the_inventory:
      '\nhas been deleted from the inventory',
    has_been_added_to_the_inventory: '\nhas been added to the inventory',
    welcome: 'Welcome!',
    your_testing_account_has_been:
      'Your testing account has been created and your login information has been sent to your email inbox. Please visit web administration.',
    take_me_to_web: 'Take me to web',
    transfer: 'transfer',
    Inventories: 'Inventories',
    main_inventory: 'Main Inventory',
    show_item: 'Show items',
    sorting_by: 'Sorting by ',
    add_product: 'add item',
    clear: 'Clear all',
    apply: 'Apply',
    Filter: 'Filter',
    sort_by: 'Sort by',
    transfer_product: 'Transfer items',
    review_transfer: 'Review the transfer',
    from: 'From',
    to: 'To',
    no_product_found: 'No Items Found',
    we_have_found_the_product:
      'We haven’t found the item you’re looking for in %@%. Please check your typos and make sure you’re searching in the right inventory.',
    we_have_not_found_the_product: 'We haven’t found any item in %@%.',
    search_product: 'Search item',
    expiration_Earliest_date: 'Expiration date (Earliest first)',
    expiration_leatest_date: 'Expiration date (Latest first)',
    date_update: 'Date Updated',
    selectlocation_title: 'Select location',
    from_text: 'From',
    to_text: 'To',
    select_location: 'Select location...',
    exp: 'Exp:',
    select_location_from: 'Select location - From',
    select_location_to: 'Select location - To',
    add_to_list: 'ADD TO LIST',
    add_product_transfer_list: 'Add items \nto transfer list',
    search_product_transfer_list: 'Search items to transfer...',
    Product_transfer: 'Items to transfer ',
    Product_transfer_close_bracket: ')',
    Enter_quantity_to_transfer: 'Enter quantity to transfer',
    Adjust_quantity_to_transfer: 'Adjust quantity to transfer',
    Quantity_of: 'Quantity of ',
    has_been_adjusted: ' has been adjusted.',
    products_have_been_moved_to: '%d %p have been moved to %@',
    products_has_been_moved_to: '%d %p has been moved to %@',
    product: 'item',
    products: 'items',
    undo: 'UNDO',
    quantity_must_be_less_or_equal_to:
      'Total check out quantity must be less or equal to ',
    search_product_checkout: 'Search items to check out...',
    adjust_qty_checkout: 'Adjust quantity to check out',
    enter_qty_checkout: 'Enter quantity to check out',
    review_product_to_checkout: 'Review the items \nto checkout',
    select_item: 'Select inventory',
    add_new_product: 'Add new item to inventory',
    inventory_name: 'Inventory name',
    select_inventory: 'Select inventory...',
    product_have_been_checkout: '%d %p have been checked out of %@',
    product_has_been_checkout: '%d %p has been checked out of %@',
    pick_product_to_check_out: 'Pick items \nto check out',
    add_product_checkout_list: 'Add items \nto checkout list',
    Product_check_out: 'Items to check out ',
    select_inventory_check_out: 'Select an inventory\nto check out of',
    pick_product_to: 'Pick items to check out',
    checkout_is_locked: 'Checkout is locked',
    you_dont_have_permission:
      'You don’t have permission to check items out of any inventory. Ask your organisation manager to make you an editor of an inventory to be able to check items out. ',
    has_been_added_to_the: '\nhas been added to the %i',
    inventory_you_can_edit: 'Inventories you can edit',
    inventory_you_can_view: 'Inventories you can view',
    select_availability: 'Select availability ...',
    selected_supplier_: 'Select suppliers ...',
    search_in: 'Search in ',
    upload_delivery: 'Upload delivery note',
    you_not_permission:
      'You don’t have permission to accept deliveries. Ask your organisation manager to make you an editor of an inventory to be able to accept deliveries for that inventory.',
    select_all: 'Select all',
    the_product_not_found:
      'The item you’re looking for was not \nfound in this order. Please check your \ntypos and make sure you’re searching \ninside the right order.',
    search_product_order: 'Search items in this order...',
    adjudt_quantity: 'Adjust quantity',
    reset: 'Reset',
    what_the_quantity: 'What’s the quantity you’re accepting to the inventory?',
    what_was_wrong: 'What was wrong with this \nitem? ',
    delivery_lock: 'Delivery is locked',
    show_report_for: 'Show reports for:',
    weekly: 'Weekly Report',
    supplier_delivered_less: 'Supplier delivered less than ordered',
    account: 'Account',
    exps: 'exp. ',
    last_update: 'Last updated',
    there_were_other_issues: 'There were other issues',
    added: 'Added',
    at: 'at ',
    product_packaging_was_damaged: 'Item packaging was damaged',
    some_item_did_look_fresh: 'Some items didn’t look fresh',
    some_item_expire_too: 'Some items expire too soon after delivery',
    there_were_sign_of_pests: 'There were signs of pests',
    product_was_not_delivered: 'Item was not delivered',
    supplier_delivered_more: 'Supplier delivered more than ordered',
    you_are_not_allowed_to_enter_the_decimal:
      'You are not allowed to enter the decimal or the special characters',
    this_date_does_not_exist: 'This date doesn’t exist',
    this_date_must_be: 'The date must be today or in the future',
    edit_expiration_date: 'Edit expiration date',
    invalid_date: 'invalid date',
    expmodal: 'Exp.',
    day_ago: 'days ago',
    sunday: 'Sun',
    monday: 'Mon',
    tuesday: 'Tue',
    wednesday: 'Wed',
    thursday: 'Thu',
    friday: 'Fri',
    saturday: 'Sat',
    others: ' others',
    other: ' other',
    yesterday: 'yesterday ',
    no_product_to: 'No items\nto check out',
    no_product_transfer: 'No items\nto transfer',
    quantity_to_check_out2: 'Quantity to check out',
    in: 'in',
    of: ' of ',
    Check_out_to_use: 'Check out to use',
    Check_out_as_food_waste: 'Check out as food waste',
    Why_did_it_get_wasted: 'Why did it get wasted?',
    Only_pick_one_of_the_following_reasons:
      'Only pick one of the following reasons.',
    Total_to_check_out: 'Total to check out',
    add_to_checkout_list: 'add to checkout list',
    start_stock_count: 'start inventory count',
    stock_count: 'Inventory Count',
    search_product_count: 'Search items to count...',
    count: 'Count',
    counted_items: 'Counted items (',
    update_inverntory: 'Finish Inventory Count',
    how_much_currently_in_storage:
      'How much / how many do you \ncurrently have in storage? ',
    purchase_units: 'purchase units',
    stocktaking_units: 'stocktaking units',
    basic_measurement_units: 'basic measurement units',
    add_to_counted_items: 'add to counted items',
    you_havent_counted_any_items_yet: 'You haven’t counted any items yet',
    swipe_left_to_edit:
      'Swipe left to edit an item or remove it from the counted items',
    ok_got_it: 'Ok, got it',
    we_have_not_found_the_item:
      'We haven’t found the item you’re looking for in%@%. Please check your typos and make sure you’re searching in the right inventory. ',
    counted: 'Counted',
    quite_the_stock_count: 'Quit the inventory count?',
    any_changes_you_made: 'Any changes you made so far will not be saved.',
    yes_quit: 'yes, quit',
    no_stay: 'no, stay',
    has_been_removed: 'has been removed from counted items.',
    has_been_changed: ' has been changed. ',
    add_a_new_item_to_counted_items: 'Add a new item \nto counted items',
    enter_item_name: 'Enter item name...',
    how_do_you_measure_or_count_item:
      'How do you measure or count this item when you count stock?',
    specify_conversion_to_stocktaking:
      'Specify conversion to stocktaking units...',
    how_many_stocking:
      'How many stocktaking units are there in one purchase unit?',
    select_basic_measurement_unit: 'Select basic measurement unit...',
    specify_conversion_to_bmu: 'Specify conversion to bmu...',
    item_name: 'item name',
    pick_an_expirationdate: 'Pick an expiration date...',
    total_value: 'Total Value',
    total_item_value: 'Total Item value',
    save_item: 'save item',
    quite_adding_item: 'Quit adding an item? ',
    there_nothing_inventory: 'There’s nothing in this inventory yet',
    start_by_counting_adding:
      'Start by counting and adding your current stock using the + ADD button in the top left corner.',
    great_job: 'Great job!',
    you_have_counted: 'You’ve counted all the items in',
    has_been_updated: 'has been updated',
    search_item_in: 'Search items in',
    please_wait: 'Please Wait...',
    has_been_counted_items: 'has been added to counted items',
    orders: 'Orders',
    partiallydelivered: 'partially delivered',
    cannot_see_some_of_your_recent_order:
      'Can’t see some of your recent orders? \nPress the refresh button to update the list.',
    schedule_order: 'scheduled order ',
    partially_delivered_order: 'partially delivered order',
    delivered_order: 'delivered order ',
    mark_as_deliverd_update_inventory: 'mark as delivered \n& Update inventory',
    item_selected: 'items selected',
    issue_reported: 'issues reported',
    report_issue_with: 'Report an issue with the delivery (optional)',
    you_are_accepting:
      'You’re accepting different quantity than you originally ordered. Is there any problem?',
    what_is_wrong: 'What is wrong with this item? ',
    would_you_like_to: 'Would you like to save your changes?',
    the_order_has_been_to_moved:
      'has been updated.\nThe order has been moved to partially delivered orders.',
    the_order_has_been_to_delivered_moved:
      'has been updated.\nThe order has been moved to delivered orders.',
    no_issue_reported: 'No issues reported',
    you_have_no_partially_orders: 'You have no partially delivered orders',
    location: 'Location',
    t: 'T',
    this_icon:
      'This icon indicates a theoretical expiration date - calculated based on the date of arrival and the item category. We add the theoretical expiration date automatically, if you don’t provide an actual expiration date.',
    quantity_s: 'quantity',
    arrived_on: 'Arrived on:',
    days_storage: 'Days in storage:',
    please_select_inventory_name: 'Please select inventory name field',
    continue_stock_count: 'Continue Inventory Count',
    add_stock_count: 'Add New Inventory Count',
    pick_inventory_count: 'Pick Inventories to \ncount',
    this_inventory_already:
      'This inventory is already part of \nanother inventory count',
    there_can_be_active_stock:
      'There can be just one active inventory count \nper inventory.',
    finish_stock_count: 'finish inventory count',
    any_change_to_item_quantity:
      'Any changes to item quantities you or \nyour colleagues made so far will not be \nsaved and the inventory won’t be \nupdated. You won’t be able to access this \ninventory count again.',
    cancel_the_stock_count: 'Cancel the inventory count? ',
    cancel_the_stock_count_count_btn: 'yes, cancel the inventory count',
    return_stock_count: 'no, return to the inventory count',
    this_filter_is_disable:
      'This filter is disabled because \nthere’s just one inventory in this \ninventory count',
    we_can_only_showing_inventories:
      'We’re only showing inventories you can edit. If the inventory you’re looking for doesn’t appear in here, please head over to the Settings / Main Inventories section in the web app to make sure you have permission to edit it.',
    mark_multiple_item_out_of_stock: 'Mark multiple items as out of stock',
    share_stock_count_report: 'Share inventory count report',
    rename_stock_count: 'Rename inventory count',
    cancel_stock_count: 'Cancel inventory count',
    enter_stock_count_name: 'Enter inventory count name',
    finish_stock_count_Data: 'There aren’t any finished \ninventory counts',
    in_progress_stock_count: 'There aren’t any inventory \ncounts in progress',
    no_stock_counted_data: 'You haven’t counted \nanything yet',
    mak_yoghurt_forest: 'Mark \nas uncounted?',
    this_will_reset_quntity:
      'This will reset its quantity and move it \nback to the list of uncounted items.',
    yes_mark_as_uncounted: 'yes, mark as uncounted',
    no_keep_it: 'no, keep it as it is',
    save_changes: 'save changes',
    finish_stockcount_and_update:
      'Finish inventory count and update \nthe inventory?',
    finish_stockcount_and_update_inventoris:
      'Finish inventory count and update \nthe inventories?',
    there_are_uncounted_item:
      'Once you finish the inventory count, you will \nno longer be able to change the \nquantities of the inventory items in this \ninventory count.',
    finsih_stock_count: 'yes, finish inventory count',
    discard_filter_changes: 'Discard filter changes?',
    you_made_some_changes:
      'You’ve made some changes to filters. \nWould you like to apply these changes  or \ndiscard them?',
    yes_apply_filter_changes: 'yes, apply filter changes',
    no_discard_filter_changes: 'No, discard filter changes',
    mark_as_out_of_stock: 'Mark as out of stock',
    clear_filters: 'Clear filters',
    only_showing_inventories:
      'Only showing inventories that are part of this \ninventory count',
    filter_by_inventory: 'Filter by inventory',
    filter_by_category: 'Filter by category',
    you_have_counted_all_the_items: 'You’ve counted all the items.',
    you_havenot_counted_anything_yet: 'You haven’t counted\nanything yet.',
    No_counted_item: 'No counted items match \nthe filters',
    filters_are_on_counted:
      'Filters are on. There are counted items in \nthis list but none of them match the \nactive filters. If you want to see them, try \nclearing the filters first.',
    No_Uncounted_item: 'No uncounted items match \nthe filters',
    filters_are_on_unCounted:
      'Filters are on. There are uncounted items \nin this list but none of them match the \nactive filters. If you want to see them, try \nclearing the filters first.',
    rename: 'rename',
    month: 'Month',
    stock_count_name: 'inventory count name',
    select_uncounted_item: 'Select uncounted items',
    sarch_uncounted_item: 'Search uncounted items...',
    category: 'Category',
    we_have_found_the_stock_count_item:
      'We haven’t found the item you’re looking \nfor. There are active filters, try clearing \nthem first.',
    we_have_not_found: 'We haven’t found the item \nyou’re looking for.',
    filter_by_month: 'Filter by month',
    no_in_progress_stock: 'No in progress inventory counts \nmatch the filters',
    no_in_progress_stock_subText:
      'Filters are on. There are inventory counts in \nprogress, but none of them match the \nactive filters. If you want to see them, try \nclearing the filters first.',
    no_in_finish_stock: 'No finished inventory counts \nmatch the filters',
    no_in_finish_stock_subText:
      'Filters are on. There are finished stock \ncounts, but none of them match the \nactive filters. If you want to see them, try \nclearing the filters first.',
    edit_quntity: 'Edit quantity',
    mark_as_uncounted: 'Mark as uncounted',
    no_stock_count_found: 'No Inventory Counts \nFound',
    start_a_new_stock_count: 'start a new inventory count',
    we_have_found_stock_count_search:
      'We haven’t found the inventory count you’re \nlooking for. There are active filters, try \nclearing them first.',
    stock_count_has_been_finish:
      ' inventory count has been finished and all involved inventories have been updated. We’ve sent the inventory count report to ',
    stock_count_has_been_cancelled: ' inventory count has been cancelled. ',
    has_been_moved_to_uncounteditem: ' has been moved to uncounted items. ',
    the_quantity_of: ' The quantity of ',
    finished: 'Finished',
    try_again_in_few_moments: 'Try again in a few moments',
    can_not_accress_this_item: 'Can’t access this item because \n',
    is_currently_editing: ' is currently \nediting it',
    add_this_item_to_stock_count: 'Add this item to inventory count',
    is_edit_this_item: ' is editing this item',
    has_been_added_to_counted_item: ' has been added to counted items. ',
    item_have_been_marks_as_out_of:
      ' items have been marked as out of stock and moved to the counted items.',
    no_go_back: 'No, go back',
    If_you_finish_the_stock_count_now:
      'There are still some uncounted items.\nIf you finish the inventory count now, they \nwill be left as they are (their quanities \nwon’t be updated).',
    in_progress: 'in progress',
    uncounted: 'uncounted',
    show: 'show',
    has_been_rename: ' has been renamed to ',
    are_still_counting: ' are still counting stock.',
    is_still_counting: ' is still counting stock.',
    search_item: 'Search items...',
    there_is_more_uncounted:
      'There are more uncounted items in this list. Clear \nthe filters to be able to see them.',
    if_you_finish_the_stock_count:
      'If you finish the inventory count now, they \nwon’t be able to continue and the \nuncounted items will be left as they are \n(their quanities won’t be updated).',
    latest_stock_count: 'Latest inventory count',
    other_user_have_finished: 'Other user have finished this inventory count.',
    can_not_access_this_stock_count:
      "Can’t access this inventory count because \n other user has currently \nfinished it's inventory count",
    your_report_is_being:
      'Your report is being in process. Please try \nafter sometime.',
    coming_soon: 'Coming soon',
    finish_stock_count_and_updating:
      'Finishing inventory count and \nupdating the inventory...',
    stock_count_has_been_finished: 'Inventory count has been finished',
    all_the_involved_inventory:
      'All the involved inventories have been \nupdated. We’ve sent the inventory count \nreport to ',
    something_went_wrong: 'Something went wrong',
    we_could_not_finish_the_stockcount:
      'We couldn’t finish the inventory count and\n update the involved inventories. \nPlease check your internet connection \nand try again in a few moments.',
    clear_all_item: 'Clear all items \nin the checkout list?',
    cancel_checkout_item: 'Cancel checkout?',
    this_action_is: 'This action is irreversible',
    if_you_cancel_the_checkout:
      'If you cancel the checkout, all the items \nin the checkout list will be cleared.',
    yes_clear_all_item: 'Yes, clear all items',
    yes_cancel_checkout: 'Yes, cancel checkout',
    no_do_not_clear_them: 'No, don’t clear them',
    no_cancel_it: 'No, don’t cancel it',
    which_inventory_should_Update:
      'Which inventory should be updated when you \nmark items in this order as delivered?',
    there_is_nothing_checkout: 'There’s nothing to check out.',
    remove_from_the_checkout_list: ' has been removed from the checkout list.',
    checkout_quantity_of: 'Checkout quantity of ',
    confirm_checkout: 'Confirm checkout',
    are_you_sure_you_want_checkout: 'Are you sure you want to check out of ',
    confirm_check_out: 'confirm check out',
    go_back_to_checkout: 'go back to checkout list',
    yes_cancel_transfer: 'Yes, cancel transfer',
    cancel_transfer_item: 'Cancel transfer?',
    if_you_cancel_the_transfer:
      'If you cancel the transfer, all the items in the transfer list will be cleared.',
    clear_all_item_Transfer: 'Clear all items \nin the transfer list?',
    after_transfer: 'After transfer',
    after_checkout: 'After checkout',
    transfer_add_snack_text: 'have been added to the transfer list.',
    remove_from_the_transfer_list: ' has been removed from the transfer list.',
    update_text: 'has been updated',
    transfer_update_text: 'Transfer quantity of',
    checkout_update_text: 'Checkout quantity of',
    checkout_add_snack_text: 'have been added to the checkout list.',
    remove_from_transfer_list: 'Remove from transfer list',
    remove_from_checkout_list: 'Remove from checkout list',
    total_to_transfer: 'Total to transfer',
    confirm_transfer: 'Confirm transfer',
    are_you_sure_you_want_transfer: 'Are you sure you want to transfer ',
    items: 'items',
    go_back_to_transfer: 'go back to transfer list',
    out_of: 'out of',
    has_been_cancelled: 'has been cancelled.',
    transfer_of_items_from: 'Transfer of items from',
    checkout_of_items_from: 'Checkout of items from',
    checkout_success_snack_text: 'item have been checked out of',
    checkout_success_snack_second_text: 'items have been checked out of',
    placeholder_text: 'e.g 100.00',
    cost_per: 'Cost per',
    no_internet_connection_test: 'No internet connection',
    no_internet_connection_subtext: 'We’re unable to load your data.',
    retry_text: 'retry',
    you_can_edit: 'you can edit',
    you_can_view: 'you can view',
    connection_lost: 'Connection lost',
    connection_lost_message:
      'Demo App app functionalities might be limited or not available until you are back online.',
    no_internet_connection_popup_subtext:
      'You’re offline. Please check your connection and try again in a few moments.',
    add_item_to_an_inventory: 'Add item to an inventory',
    transfer_items_between_inventories: 'Transfer items between inventories',
    no_inventories_edit: 'No inventories\nyou can edit',
    no_inventories_view: 'No inventories\nyou can view',
    cost_summary: 'Cost summary',
    cost_summary_sub_text:
      'Cost summary is just an approximation using latest order prices. Final item cost in the finished inventory count might be slightly different because it takes into account price variations of the inventory item.',
    show_zero: '0.00',
    approximate_total_value: 'approximate total value',
    cost_summery_popup_text:
      'The approximate total value of counted items is an estimate based on the latest order prices. Final total value in the finished inventory count might be slightly different because it takes into account price variations of inventory items.',
    reopen_stock_count: 'Reopen inventory count',
    reopen_popup_title: 'Reopen the inventory count?',
    reopen_popup_text:
      'Reopening a finished inventory count allows you to make corrections or adjustments to the recorded item quantities.',
    reopen_popup_text_second:
      'New inventory count report will be automatically generated when you finish the inventory count again.',
    reopen: 'reopen',
    stock_count_finish_in_the_process: 'Inventory count finish in the process',
    stock_count_finish_in_the_process_text:
      'your inventory count finish process is starting and we will inform you by the notification once the inventory count has been finished',
    bluetooth_allow_title_text: 'Demo App would like to use Bluetooth',
    bluetooth_allow_sub_text:
      'Demo App app needs Bluetooth to connect to the RFID scanner',
    allow: 'Allow',
    bluetooth_is_off: 'Bluetooth is off',
    bluetooth_is_off_sub_text:
      'Go to Settings and turn on Bluetooth to be able to connect your phone to the RFID scanner',
    open_settings: 'open settings',
    searching_for_RFID_scanner: 'Searching for RFID scanner',
    searching_for_RFID_scanner_sub_text:
      'Bring your phone closer to the RFID scanner, and ensure that the RFID scanner is turned on',
    connect: 'Connect',
    connecting: 'Connecting...',
    is_connected_to_your_phone: 'is connected to your phone',
    RFID_scanner: 'RFID scanner',
    scan_RFID: 'Scan RFID',
    gather_items_for_scanning_in_one: 'Gather items for scanning in one',
    place_Aim_your_RFID_scanner_at_them: 'place Aim your RFID scanner at them',
    press_the_scanner_button_to_see_the_items_and_their_quantities_here:
      'Press the scanner button to see the items and their quantities here',
    scanned_items: 'Scanned items',
    confirm_items: 'Confirm Items',
    add_a_new_item: 'Add a new item to counted items',
    to_Demo: 'to Demo App',
    signup_text: 'By signing up, you agree to the',
    and: 'and',
    terms_of_use: 'Terms of Use',
    privacy_policy: 'Privacy Policy.',
    your_full_name: 'Your Full Name',
    your_role: 'Your Role',
    company_type: 'Company Type',
    select_company_type: 'Select company type...',
    country: 'Country',
    select_country: 'Select country...',
    let_start: 'let’s start',
    eight_characters_minimum: '8 characters minimum',
    please_fill_in_all_the_required_information:
      'Please fill in all the required information',
    this_information_is_required: 'This information is required',
    please_select_an_option: 'Please select an option',
    please_specify_company_type: 'Please specify company type...',
    inventory_count_made_easy: 'Inventory Count Made Easy',
    welcome_message_text:
      'Demo App helps you reduce inventory count time in your hotel or restaurant and cut food waste by up to 35%.',
    copyright_text: '© 2020 Demo App. All rights reserved.',
    password_error: 'Password must be at least 8 characters long',
    incorrect_email:
      'Incorrect e-mail format. Please check for a missing "@" or domain.',
    already_use_email_error:
      'It looks like there’s already an account with this email. Please log in or use another e-mail address.',
    select_company_type_title: 'Select Company Type',
    select_country_title: 'Select Country',
    one_step_closer: 'One step closer!',
    initial_inventory_title_text:
      'Now it’s time to set up your initial inventory',
    initial_inventory_sub_text:
      'To import your inventory to Demo App, please switch to the Demo App Admin app in your web browser on desktop or laptop.',
    initial_inventory_sub_text_second:
      'We’ve sent you an email with the Demo App Admin link and steps to follow.',
    there_nothing_inventory_sub_text:
      'To comfortably upload all your inventory items, please switch to Demo App Admin app on a desktop or laptop computer.',
    e_g_general_manager: 'e.g. General Manager',
    please_fill_valid_total_product_cost: 'please fill valid total item cost',
    email_is_required: 'Email is required',
    invalid_email: 'Invalid Email',
    ok: 'ok',
    verification_code_required: 'Verification code is required',
    invalid_verify_code: 'Invalid Verification Code',
  };
};
