export const stringsNB = () => {
  return {
    this_is_demo: 'This is just a demo app',
    login: 'logg inn',
    forgot_password: 'Glemt passord',
    password: 'passord',
    recover_password: 'Gjenopprett passord',
    forgot_your_password: 'Glemt ditt passord?',
    forgot_password_big_text:
      'Angi din epostadresse og vi vil sende deg instruksjoner på hvordan å gjenopprette passordet ditt',
    email_sent: 'Epost sendt',
    enter_the_code_we_sent: 'Angi koden vi sendte deg',
    to_recover_your_password: 'til å gjenopprette passordet ditt',
    enter_code: 'Angi kode',
    continue: 'Fortsett',
    new_password: 'Nytt passord',
    enter_new_password: 'Angi ditt nye passord',
    save_and_login: 'Lagre og logg inn',
    are_you_sure_to_reset_password:
      'Er du sikker på at du vil avbryte gjenopprettingsprosessen for passord? Avbryter du vil den ikke bli tilbakestilt',
    interrupt: 'Avbryt',
    go_back: 'Gå tilbake',
    profile: 'Profil',
    full_name: 'Fullt navn',
    change_password: 'Endre passord',
    logout: 'Logg ut',
    inventory: 'Varelager',
    inventories: 'Varelager',
    add_item: 'Legg til vare',
    change_password_title: 'Endre passord',
    current: 'Nåværende',
    new: 'Ny',
    enter_your_current_password: 'Angi ditt nåværende passord',
    enter_your_new_password: 'Angi ditt nye passord',
    save: 'lagre',
    save_the_changes: 'Lagre endringene?',
    yes_save: 'Ja, lagre',
    no_discard: 'Nei, forkast',
    inventory_title: 'Varelager',
    your_inventory_is_empty: 'Ditt lager er tomt',
    enter_product_name_to_search: 'Angi produktnavn for å søke',
    add_manually: 'Legg til manuelt',
    enter_product_name: 'Skriv inn produktnavn',
    save_Button: 'lagre',
    done: 'Ferdig',
    quantity: 'Antall',
    supplier: 'Leverandør',
    group: 'Gruppe',
    select_product_group: 'Velg produktgruppe',
    enter_quantity_in_kg: 'Angi antall kg',
    enter_quantity: 'Angi antall',
    item_has_been_added_to_inventory: 'Vare har blitt lagt til lageret',
    number_of_cartons_in_a_pallet: 'Antall kartong i en pall',
    number_of_piece_in_a_carton: 'Antall stykk i en kartong',
    crt_in_pall: 'krt i pall',
    pcs_in_crt: 'stk i krt',
    enter: 'Angi',
    pcs: 'stk',
    crt: 'Krt',
    pall: 'Pall',
    expires_on: 'Går ut på',
    select_expiration_date: 'Velg utløpsdato',
    select_product_group_title: 'Velg produktgruppe',
    gtin_type: 'Gtin type',
    add_Weighed: 'Legg til vekt',
    scan_barcode: 'Skann strekkode',
    change: 'Endre',
    please_fill_in_all_obligatory_fields:
      'Vennligst fyll ut alle obligatoriske felt',
    enter_supplier_name: 'Angi leverandør Navn',
    select_supplier: 'velg leverandør',
    edit_Item: 'Rediger vare',
    scan_barcode_to_search: 'Skann strekkode for å søke',
    save_Changes: 'Lagre endringer',
    item_not_in_stock: 'Produktet er ikke i lageret',
    do_you_want_to_delete: 'Vil du slette',
    from_the_warehouse: 'fra lageret?',
    the_item_has_been_added_to_the_stock:
      'Produktet har blitt lagt til lageret',
    please_select_Vendor: 'Vennligst velg leverandør',
    item_group_name_and_group_code: 'Varens gruppenavn og gruppekode',
    cancel: 'Avbryt',
    kart_per_pallet_should_not_be_zero: 'krt per pall kan ikke være null',
    pcs_per_kart_should_not_be_zero: 'stk per krt kan ikke være null',
    quantity_should_not_be_zero: 'Antall kan ikke være null',
    pcs_carts_palls_should_not_be_null:
      'stk/krt eller krt/pall kan ikke være null',
    pcs_kart_should_not_be_null: 'stk/krt kan ikke være null',
    continue_editing: 'Fortsett redigering',
    do_you_want_to_delete_this_entry: 'Vil du slette denne oppføringen?',
    you_are_not_allowed_to_enter_the_special_characters:
      'Du kan ikke bruke spesiale tegn eller bokstaver',
    add_to_stock: 'Legg til lageret',
    add_products: 'Legg til flere produkter',
    your_password_has_been_changed: 'Ditt passord har blitt endret',
    click_on_recover_password_below:
      'Klikk på Tilbakestill passord så sender vi deg en epost til',
    with_instructions_on_how_to_recover_your_password:
      'med instruksjoner på hvordan tilbakestille ditt passord ',
    yes_delete: 'Slett',
    move_on: 'Fortsett',
    localeDate: 'nb',
    localPath: 'moment/locale/en-au',
    cancel_process: 'Avbryt utsjekksprosessen for',
    if_you_cancel:
      'Hvis du avbryter utsjekk for dette produktet vil ikke antallet for produktet i lageret bli oppdatert',
    cancel_checkin: 'Avbryt utsjekk',

    cancel_checkout_process: 'Avbryt utsjekksprosess for',
    if_you_cancel_checkout:
      'Hvis du avbryter utsjekk for dette produktet vil antallet for produktet i lageret ikke bli oppdatert',
    cancel_checkout: 'avbryt utsjekk',

    enter_email_address: 'Tast inn din epost',
    enter_password: 'Angi passord',
    check_in_delivered_products: 'Sjekk inn leverte produkter',
    search_product_to_check_in: 'Søk etter produkt til å sjekke inn',
    barcode: 'strekkode',
    barcode_type: 'Type strekkode',
    what_type_of_barcode_did_you_scan: 'Hvilken type strekkode skannet du?',
    f_pack: 'F-pakke',
    d_pack: 'D-pakke',
    t_pack: 'T-pakke',
    tips_text:
      'Tips: Inkluder en målingsenhet i produktnavnet (f.eks Coriander, bunt eller Tap øl, tønne 30 L). Dette hjelper deg å skille produktene når du søker eller går gjennom lageret ',
    check_out_of_inventory: 'Sjekk ut av lageret ',
    please_select_product_batch_first: 'Vennligst velg produktparti først',
    we_have_only: 'Vi har bare ',
    available: 'tilgjengelig',
    how_many_would_you_like_to_check_out: 'Hvor mange vil du sjekke ut?',
    select_product_batch: 'Velg produktparti',
    expiration_date_not_available: 'Utløpsdato er ikke tilgjengelig',
    quantity_to_check_out: 'Antall til utsjekk',
    has_been_deleted_from_inventory: 'har blitt slettet fra lageret',
    days_left: 'dager igjen',
    the_change_has_been_saved: 'Endringene har blitt lagret ',
    check_in_to_inventory: 'Sjekk inn på lageret ',
    add_product_manually: 'Legg til produkt manuelt',
    this_product_is_not_in_your_inventory:
      'Dette produktet er ikke \npå lageret',
    this_product_is_not_in_the_database:
      'Dette produktet er ikke \ni databasen',
    search_product_to_check_out: 'Søk etter et produkt for å sjekke ut',
    expiring_on: 'utløper ',
    have_been_checked_out_of_inventory: 'har blitt sjekket ut av lageret ',

    //New
    personal_details: 'Personlige opplysninger',
    weekly_reports: 'Ukentlig rapporter',
    see_All: 'Se alle',

    nothing_exp_soon: 'Ingenting er i ferd med å gå ut på dato. Bra jobbet!',
    see_detail: 'Se detaljer',
    expiration_date_not_specified: 'Utløpsdato ikke spesifisert',
    ordered: 'bestilt',
    accepted: 'Akseptert',
    today: 'Idag',
    today_text: 'idag ',
    tomorrow: 'Imorgen',
    tomorrow_text: 'imorgen ',
    had_issue: 'hadde avvik',
    scheduled: 'Planlagt',
    delivered: 'levert',

    the_product_youre_looking:
      'Produktet du leter etter ble ikke funnet i denne bestillingen',
    finish_and_update_inventory: 'Fullfør og oppdater lager',
    checked: 'sjekket',
    left: 'igjen',
    add_a_note: 'Legg til en notis',
    note: 'merk',
    quality: 'kvalitet',
    is_there_anything_wrong: 'Er det noe galt?',
    add_expiration_date: 'Legg til en utløpsdato',
    expiration_date: 'Utløpsdato',
    accepting: 'Aksepterer',
    delivery: 'Levering',
    add: 'Legg til',

    pick_Order_long_text:
      'Velg en bestilling fra listen nedenfor for å begynne å \nsjekke ut leverte varer. Hvis du ikke ser bestillingen \ndin i listen, kan du ta et bilde av \nfølgeseddelen for å laste den opp til appen.',
    you_have_no_delivered_orders: 'Du har ingen leverte bestillinger',
    you_have_no_scheduled_orders: 'Du har ingen planlagte bestillinger',
    your_Inventory_has_been_updated: 'Lageret ditt har blitt oppdatert',
    specify_expiration_date: 'Angi utløpsdato',
    specify_quantity: 'Angi antall',

    add_another_expiration_date: 'Legg til en annen utløpsdato',
    show_100_items: 'Vis varer',
    clear_all: 'Fjern alle',
    availability: 'Tilgjengelig',
    in_Stock: 'På lager',
    out_of_Stock: 'Ikke på lager',
    search_inventory: 'Søk i lageret',
    your_changes_have_been_saved: 'Dine endringer har blitt lagret',
    sort: 'Sorter',
    filter: 'filter',
    //add: "legg til",
    please_fill_product_name_field: 'Vennligst fyll ut produktnavnfeltet ',
    add_new_product_to_inventory: 'Legg til nytt produkt\n til lager',
    product_name: 'Produktnavn',
    exp_Not_specified: 'Utg: ikke spesifisert',
    day_left: 'Dager igjen',
    expired: 'Utløpt',
    edit: 'Rediger',
    expires_not_specified: 'Utløpsdato ikke spesifisert',
    expires: 'Utløper',
    total_quantity: 'Totalt antall',
    no_Items_Found: 'Ingen varer funnet',
    please_check_your_typos:
      'Vennligst sjekk for skrivefeil og legg varen \ntil ditt lager først.',
    add_new_item: 'legg til ny vare',
    select_purchase_unit: 'Velg kjøpsenhet...',
    one_purchase_unit: '1 kjøpt enhet = ',
    select_stocktaking_unit: 'Velg lagerenhet...',
    setup_unit_conversions: 'Sett opp \nenhetskonverteringer',
    purchase_unit: 'Kjøpeenhet',
    stocktaking_unit: 'Lagerenhet',
    how_do_you_measure_or_count:
      'Hvordan måler eller teller du denne varen når du sjekker lageret ditt?',
    specify_conversion: 'Spesifiser konvertering',
    select_measurement_unit: 'Velg måleenhet',
    basic_measurement_unit: 'Vanlig måleenhet',
    measurement_unit: 'Målingsenhet',
    how_many_basic_measurement:
      'Hvor mange vanlige måleenheter er det i \nen lagerføringsenhet?',
    first_to_Expire: 'Først til å utløpe',
    last_to_Expire: 'Sist til å utløpe',
    recently_Updated: 'Nylig oppdatert',
    alphabet_A_Z: ' Alfabet (A-Å)',
    please_fill_in_quantity_fields: 'Vennligst fyll inn felt for antall',

    specify_quantity_and_shelf_life: 'Angi antall og utløpsdato',

    expiration_date_optional: 'Utløpsdato (frivillig)',
    please_fill_in_total_product_cost_field:
      'Vennligst fyll inn total produkt kostnadsfeltet',
    total_product_cost: 'Totalt produkt \nkostnad',

    total_product_cost_text: 'Totalt produkt kostnad',
    save_product: 'lagre produkt',

    items_will_expire_soon: ' varer utløper snart',
    log_in_to_Demo: 'Logg deg inn \npå Demo App',
    name: 'Navn',
    first_name_Last_name: 'Fornavn Etternavn',
    company_name: 'Bedrift navn',

    email: 'epost',
    your_Password: 'Ditt passord',
    eight_Characters: '8 bokstaver',
    forgotten_password: 'Glemt passord?',
    example_example_com: 'example@example.com',

    check_your_inbox: 'Sjekk din innboks',
    go_to_my_inbox: 'Gå til min innboks',

    reset_Password: 'Gjenopprett passord',
    search_items: 'Søk etter varer',

    pick_an_item_to_check_out: 'Velg en vare til å \nsjekke ut',

    not_Defined: 'Ikke definert',
    please_select_expiration_date_first: 'Vennligst velg utløpsdato først',
    Please_select_expiration_date_and_enter_quantity:
      'Vennligst velg utløpsdato og angi antall',
    please_select_expiration_date: 'Vennligst velg utløpsdato ',
    please_enter_quantity: 'Vennligst angi antall',

    check_out: 'Sjekk ut',

    we_haven_found_any_items_your:
      'Vi har ikke funnet noen varer i ditt lager som samsvarer ditt søk',
    search_results: 'Søkeresultater',
    E_mail: 'epost',
    sign_up: 'Registrer deg',
    stop_food_waste: 'Stopp matsvinn!',
    welcome_message:
      'Få kontroll over matlageret \nved hjelp av vår løsning for \nlagerbeholdning',
    has_been_deleted_from_the_inventory: '\nhar blitt slettet fra lageret',
    has_been_added_to_the_inventory: '\nhar blitt lagt til lageret',
    welcome: 'Velkommen!',
    your_testing_account_has_been:
      'Din testkonto har blitt opprettet og logg inn informasjonen har blitt sendt til din epost. Vennligst gå til web administrasjonen',
    take_me_to_web: 'Ta meg til web',
    transfer: 'overføre',
    Inventories: 'Varelagre',
    main_inventory: 'Hovedlager',
    show_item: 'Vis varer',
    sorting_by: 'Sortering etter ',
    add_product: 'legg til produkt',
    clear: 'Fjern alle',
    apply: 'Bruk',
    Filter: 'Filter',
    sort_by: 'Sorter på',
    transfer_product: 'Overfør varer',
    review_transfer: 'Gjennomgå overføringen',
    from: 'Fra',
    to: 'Til',
    no_product_found: 'Ingen produkter funnet',
    we_have_found_the_product:
      'Vi har ikke funnet produktet du leter etter i %@%. Vennligst sjekk for skrivefeil og søk på den riktige avdelingen.',
    we_have_not_found_the_product: 'Vi har ikke funnet noen produkter på %@%.',
    search_product: 'Søk produkt',
    expiration_Earliest_date: 'Utløpsdato (tidligst først)',
    expiration_leatest_date: 'Utløpsdato (senest først)',
    date_update: 'Dato oppdatert',
    selectlocation_title: 'Velg lokasjon',
    from_text: 'Fra',
    to_text: 'Til',
    select_location: 'Velg lokasjon...',
    exp: 'Utg:',
    select_location_from: 'Velg lokasjon - Fra',
    select_location_to: 'Velg lokasjon - Til',
    add_to_list: 'Legg til i liste',
    add_product_transfer_list: 'Legg produkter \ntil overføringslisten',
    search_product_transfer_list: 'Søk etter produkter å overføre ...',
    Product_transfer: 'Produkter å overføre ',
    Product_transfer_close_bracket: ')',
    Enter_quantity_to_transfer: 'Angi antall til å overføre',
    Adjust_quantity_to_transfer: 'Juster antall til å overfør',
    Quantity_of: 'Antall ',
    has_been_adjusted: 'er justert.',
    products_have_been_moved_to: '%d %p har blitt flyttet til %@',
    products_has_been_moved_to: '%d %p har blitt flyttet til %@',
    product: 'produkt',
    products: 'produkter',
    undo: 'angre',
    quantity_must_be_less_or_equal_to:
      'Total utsjekksmengde må være mindre eller lik ',
    search_product_checkout: 'Søk etter produkter for å sjekke ut ...',
    adjust_qty_checkout: 'Juster antallet til utsjekk',
    enter_qty_checkout: 'Angi antall til utsjekk',
    review_product_to_checkout: 'Gå gjennom produktene \ntil utsjekk',
    select_item: 'Velg lager',
    add_new_product: 'Legg til nytt produkt til lager',
    inventory_name: 'Lagernavn',
    select_inventory: 'Velg lager ...',
    product_have_been_checkout: '%d %p har blitt sjekket ut av %@',
    product_has_been_checkout: '%d %p har blitt sjekket ut av %@',
    pick_product_to_check_out: 'Velg produkter \nå sjekke ut',
    add_product_checkout_list: 'Legg til produkter \ntil utsjekkslisten',
    Product_check_out: 'Produkter å sjekke ut ',
    select_inventory_check_out: 'Velg et lager \nå sjekke ut fra',
    pick_product_to: 'Velg produkter til utsjekk',
    checkout_is_locked: 'Utsjekk er låst',
    you_dont_have_permission:
      'Du har ikke tillatelse til å sjekke varer ut av noe lager. Be din leder om å gi deg tillatelse til å sjekke ut varer fra et lager.',
    has_been_added_to_the: '\nhar blitt lagt til %i',
    inventory_you_can_edit: 'Lagre du kan redigere',
    inventory_you_can_view: 'Lagre du kan se',
    select_availability: 'Velg tilgjengelighet ...',
    selected_supplier_: 'Velg leverandører ...',
    search_in: 'Søk i ',
    upload_delivery: 'Last opp følgeseddel',
    you_not_permission:
      'Du har ikke tilgang til å motta leveringer. Spør din leder for tilgang til å motta leveringer for et lager.',
    select_all: 'Velg alle',
    the_product_not_found:
      'Produktet du leter etter har ikke blitt funnet i denne bestillingen. Vennligst sjekk for skrivefeil og vær sikker på at du søker i riktig bestilling.',
    search_product_order: 'Søk etter produkter i denne rekkefølgen ...',
    adjudt_quantity: 'Juster antall',
    reset: 'Nullstill',
    what_the_quantity: 'Hva er antallet du har godtatt inn til lageret?',
    what_was_wrong: 'Hva var galt med dette \nproduktet?',
    delivery_lock: 'Levering er låst',
    show_report_for: 'Vis rapport for:',
    weekly: 'Ukentlig rapport',
    supplier_delivered_less: 'Leverandør leverte mindre enn bestilt',
    account: 'Konto',
    exps: 'utg.',
    last_update: 'Sist oppdatert',
    there_were_other_issues: 'Det var flere avvik',
    added: 'Lagt til',
    at: 'kl. ',
    product_packaging_was_damaged: 'Emballasje var skadet',
    some_item_did_look_fresh: 'Noen varer så ikke fersk ut',
    some_item_expire_too: 'Noen varer utgår like etter levering',
    there_were_sign_of_pests: 'Det var tegn på skadedyr',
    product_was_not_delivered: 'Produktet ble ikke levert',
    supplier_delivered_more: 'Leverandør leverte mer enn bestilt',
    you_are_not_allowed_to_enter_the_decimal:
      'Du kan ikke bruke desimaler eller spesielle tegn',
    this_date_does_not_exist: 'Denne datoen finnes ikke',
    this_date_must_be: 'Datoen må være idag eller i framtiden',
    edit_expiration_date: 'Edit expiration date',
    invalid_date: 'invalid date',
    expmodal: 'utg.',
    day_ago: 'dager siden',
    monday: 'Man',
    tuesday: 'Tir',
    wednesday: 'Ons',
    thursday: 'Tor',
    friday: 'Fre',
    saturday: 'Lør',
    sunday: 'Søn',
    others: ' andre',
    other: ' annen',
    yesterday: 'i går ',
    no_product_to: 'Ingen produkter\nå sjekke ut',
    no_product_transfer: 'Ingen produkter\nå overføre',
    quantity_to_check_out2: 'Antall å sjekke ut',
    in: 'i',
    of: ' av ',
    Check_out_to_use: 'Sjekk ut til forbruk',
    Check_out_as_food_waste: 'Sjekk ut som matsvinn',
    Why_did_it_get_wasted: 'Hvorfor ble det kastet?',
    Only_pick_one_of_the_following_reasons: 'Velg en av følgende grunner.',
    Total_to_check_out: 'Totalt til å sjekke ut',
    add_to_checkout_list: 'Legg til utsjekksliste',
    start_stock_count: 'start varetelling',
    stock_count: 'Varetelling',
    search_product_count: 'Søker etter produkter for telling...',
    count: 'Tell',
    counted_items: 'Telte varer (',
    update_inverntory: 'Fullfør varetelling',
    how_much_currently_in_storage: 'Hvor mye / hvor mange har du på lager nå? ',
    purchase_units: 'kjøpeenhet',
    stocktaking_units: 'varelagerenhet',
    basic_measurement_units: 'vanlig måleenhet',
    add_to_counted_items: 'legg til telte varer',
    you_havent_counted_any_items_yet: 'Du har ikke telt noen varer enda',
    swipe_left_to_edit:
      'Sveip til venstre for å redigere en vare eller fjerne den fra telte varer',
    ok_got_it: 'Ok, skjønner',
    we_have_not_found_the_item:
      'Vi finner ikke varen du leter etter i %@%. Vennligst sjekk etter for skrivefeil og sørg for at du søker i riktig varelager. ',
    counted: 'Telt',
    quite_the_stock_count: 'Avslutt varetelling?',
    any_changes_you_made: 'Endringer gjort hittil vil ikke bli lagret.',
    yes_quit: ' ja, avslutt',
    no_stay: 'nei, fortsett',
    has_been_removed: 'har blitt fjernet fra telte varer.',
    has_been_changed: ' har blitt endret. ',
    add_a_new_item_to_counted_items: 'Legg til ny vare \ntil telte varer',
    enter_item_name: 'Legg inn varenavn...',
    how_do_you_measure_or_count_item:
      'Hvordan måler eller teller du denne varen når du tar varetellingen?',
    specify_conversion_to_stocktaking:
      'Spesifiser konvertering til varetellingsenhet...',
    how_many_stocking:
      'Hvor mange varetellingsenhet er det i en innkjøpsenhet?',
    select_basic_measurement_unit: 'Velg varetellingsenhet...',
    specify_conversion_to_bmu:
      'Spesifiser konverteringen til varetellingsenhet...',
    item_name: 'varenavn',
    pick_an_expirationdate: 'Velg en utløpsdato...',
    total_value: 'Total verdi',
    total_item_value: 'Total vareverdi',
    save_item: 'lagre vare',
    quite_adding_item: 'Avslutt å legge inn vare? ',
    there_nothing_inventory: 'Det er ingenting i dette varelageret nå',
    start_by_counting_adding:
      'Start med å telle og legge til ditt nåværende lager ved å bruke «+Legg til» knappen oppe i venstre hjørnet.',
    great_job: 'Bra jobbet!',
    you_have_counted: 'Du har telt alle varer i',
    search_item_in: 'Søk etter varer i',
    please_wait: 'Vennligst vent...',
    has_been_counted_items: 'har blitt lagt til dine telte varer',
    orders: 'Ordre',
    partiallydelivered: 'delvis levert',
    cannot_see_some_of_your_recent_order:
      'Kan du ikke se noen av dine siste ordre? Trykk på oppdater-knappen for å oppdatere listen',
    schedule_order: 'planlagt ordre',
    partially_delivered_order: 'delvis levert ordre',
    delivered_order: 'leverte ordre',
    mark_as_deliverd_update_inventory:
      'marker som levert og oppdater varelager',
    item_selected: 'varer valgt',
    issue_reported: 'rapporterte problemer',
    report_issue_with: 'Rapporter et problem med leveringen (valgfritt)',
    you_are_accepting:
      'Du aksepterer et annet antall enn det du først bestilte. Er det noe galt?',
    what_is_wrong: 'Hva er galt med dette produktet? ',
    would_you_like_to: 'Vil du lagre endringene?',
    the_order_has_been_to_moved:
      'har blitt oppdatert. Orderen er flyttet til delvis leverte ordre.',
    the_order_has_been_to_delivered_moved:
      'har blitt oppdatert. Orderen er flyttet til leverte ordre.',
    no_issue_reported: 'Ingen problemer rapportert',
    you_have_no_partially_orders: 'Du har ingen delvis levert bestillinger',
    has_been_updated: 'har blitt oppdatert.',
    location: 'Plassering',
    t: 'T',
    this_icon:
      'This icon indicates a theoretical expiration date - calculated based on the date of arrival and the item category. We add the theoretical expiration date automatically, if you don’t provide an actual expiration date.',
    quantity_s: 'antall',
    arrived_on: 'Ankom den:',
    days_storage: 'Dager pÂ lager:',
    please_select_inventory_name: 'Vennligst velg Lagernavnfeltet',
    continue_stock_count: 'Fortsett Varetelling',
    add_stock_count: 'Legg til ny varetelling',
    pick_inventory_count: 'Velg lagrene som skal \ntelles',
    this_inventory_already: 'Dette lageret tilhører \nallerede en varetelling',
    there_can_be_active_stock:
      'Det er bare mulig med en aktiv varetelling \nper varelager.',
    finish_stock_count: 'Fullfør varetelling',
    any_change_to_item_quantity:
      'Endinger som du eller dine kollegaet har \ngjort i vareantall så langt vil ikke lagres, og \nvarelageret vil ikke \noppdateres. Du vil ikke kunne åpne denne \nvaretellingen igjen.',
    cancel_the_stock_count: 'Vil du avbryte varetellingen? ',
    cancel_the_stock_count_count_btn: 'Ja, avbryt varetellingen',
    return_stock_count: 'Nei, gjenoppta varetellingen',
    this_filter_is_disable:
      'Dette filteret er ikke tilgjengelig \nettersom det bare er ett aktivt varelager i denne varetellingen',
    we_can_only_showing_inventories:
      'Vi viser bare varelager du har tilgang til å redigere. Hvis du ser etter et annet lager enn det som vises her, vennligst gå til innstillinger / rediger varelager i web appen for å se om du har tilgang til å redigere det.',
    mark_multiple_item_out_of_stock: 'Angi flere varer som ikke på lager',
    share_stock_count_report: 'Del varetellingsrapport',
    rename_stock_count: 'Gi varetellingen et nytt navn',
    cancel_stock_count: 'Avbryt varetelling',
    enter_stock_count_name: 'Legg inn navn på varetellingen',
    finish_stock_count_Data: 'Det finnes ingen fullførte \nvaretellinger',
    in_progress_stock_count: 'Det finnes ingen \npågående varetellinger',
    no_stock_counted_data: 'Du har ikke telt noe ennå',
    mak_yoghurt_forest: 'Angi som \nikke telt',
    this_will_reset_quntity:
      'Dette vil tilbakestille antallet og flytte varen \ntilbake til listen med ikke-telte varer.',
    yes_mark_as_uncounted: 'Ja, angi som ikke-telt',
    no_keep_it: 'Nei, behold som den er',
    save_changes: 'Lagre endringer',
    finish_stockcount_and_update:
      'Fullfør varetelling og \noppdater varelageret?',
    finish_stockcount_and_update_inventoris:
      'Fullfør varetellingen og \noppdater varelagrene?',
    there_are_uncounted_item:
      'Når du har fullført varetellingen kan du ikke lenger redigere antall varer.',
    finsih_stock_count: 'Ja, fullfør varetellingen',
    discard_filter_changes: 'Forkast filtervalg',
    you_made_some_changes:
      'Du har gjort endringer i filterene. Ønsker du å bruke disse endringene eller å \nforkaste dem?',
    yes_apply_filter_changes: 'Ja, ta endringene i bruk',
    no_discard_filter_changes: 'Nei, forkast endringene',
    mark_as_out_of_stock: 'Angi som ikke på lager',
    clear_filters: 'Tøm filtrene',
    only_showing_inventories:
      'Viser kun varelager som er del av denne \nvaretellingen',
    filter_by_inventory: 'Filtrer etter varelager',
    filter_by_category: 'Filtrer etter kategori',
    you_have_counted_all_the_items: 'Du har telt alle varene',
    you_havenot_counted_anything_yet: 'Du har ikke telt noe ennå',
    No_counted_item: ' Ingen telte varer samsvarer \nmed filterene',
    filters_are_on_counted:
      'Filtere er valgt. Det finnes telte varer i \ndenne listen, men ingen av dem samsvarer \nmed de valgte filtrene. Hvis du ønsker å se \ndisse varene, tøm filtrene først.',
    No_Uncounted_item: 'Ingen utelte varer samsvarer \nmed filtrene',
    filters_are_on_unCounted:
      'Filtere er valgt. Det finnes utelte varer \ni denne listen, men ingen av dem samsvarer \nmed de valgte filtrene. Hvis du ønsker å se dem, tøm \nfiltrene først.',
    rename: 'gi nytt navn',
    month: 'Måned',
    stock_count_name: 'navn på varetellingen',
    select_uncounted_item: 'Velg ikke-telte varer',
    sarch_uncounted_item: 'Velg telte varer',
    category: 'Kategori',
    we_have_found_the_stock_count_item:
      'Vi klarte ikke å finne varen du leter \netter. Det finnes aktive filtre. Tøm disse \nfiltrene først.',
    we_have_not_found: 'Vi klarte ikke å finne \nvaren du leter etter',
    filter_by_month: 'Filtrer etter måned',
    no_in_progress_stock:
      'Ingen pågående varetelling samsvarer \nmed de valgte filtrene',
    no_in_progress_stock_subText:
      'Du har aktive filtre. Det finnes pågående \nvaretellingeer, men ingen samsvarer med de \nvalgte filtrene. Hvis du ønsker å se \ndisse varetellingene, tøm filtrene',
    no_in_finish_stock:
      'Ingen fullførte varetellinger \nsamsvarer med filtrene',
    no_in_finish_stock_subText:
      'Du har aktive filtre. Det finnes fullførte \nvaretellingeer, men ingen samsvarer med de valgte \nfiltrene. Hvis du ønsker å se disse \nvaretellingene, tøm filtrene først',
    edit_quntity: 'Rediger antall',
    mark_as_uncounted: 'Angi som ikke-telt',
    no_stock_count_found: ' Fant ingen varetellinger',
    start_a_new_stock_count: 'Start en ny varetelling',
    we_have_found_stock_count_search:
      'Vi klarte ikke å finne varetellingen du \nleter etter. Du har aktive filtre, tøm disse først \nog prøv igjen',
    stock_count_has_been_finish:
      ' varetellingen er fullført og alle de involverte varelagrene har blitt oppdatert. Vi har sendt varetellingsrapporten til ',
    stock_count_has_been_cancelled: ' Varetellingen har blitt avbrutt. ',
    has_been_moved_to_uncounteditem: ' har blitt flyttet til ikke-telte varer ',
    the_quantity_of: ' Antallet ',
    finished: 'Fullført',
    try_again_in_few_moments: 'Prøv igjen om litt',
    can_not_accress_this_item: 'Har ikke tilgang til denne varen ford \n',
    is_currently_editing: ' redigerer den nå',
    add_this_item_to_stock_count: 'Legg denne varen til i varetellingen',
    is_edit_this_item: ' redigerer denne varen',
    has_been_added_to_counted_item: ' har blitt lagt til i telte varer ',
    item_have_been_marks_as_out_of:
      ' varene har blitt markert som tomme på lager og har blitt flyttet til telte varer',
    no_go_back: 'Nei, gå tilbake',
    If_you_finish_the_stock_count_now:
      'Det finnes fortsatt noen utelte varer.\nHvis du fullfører varetellingen nå, vil disse \nvarene forbli uendret i lageret (antallet vil \nikke oppdateres).',
    in_progress: 'pågående',
    uncounted: 'utelt',
    show: 'vis',
    has_been_rename: ' navnet har blitt endret til ',
    are_still_counting: ' teller fortsatt varelageret',
    is_still_counting: ' teller fortsatt varelageret',
    search_item: 'Søk blant varer',
    there_is_more_uncounted:
      'Det er flere varer som ikke har blitt telt i denne listen. Tøm filtrene \nfor å se disse varene.',
    if_you_finish_the_stock_count:
      'Hvis du fullfører varetellingen nå vil de \nikke kunne fortsette og de utelte \nvarene vil forbli som de er \n(antallet vil ikke bli oppdatert).',
    latest_stock_count: 'Senest varetelling',
    other_user_have_finished: 'Other user have finished this inventory count.',
    can_not_access_this_stock_count:
      "Can’t access this inventory count because \n other user has currently \nfinished it's inventory count",
    your_report_is_being:
      'Your report is being in process. Please try \nafter sometime.',
    coming_soon: 'Kommer snart',
    finish_stock_count_and_updating:
      'Ferdigstiller varetellingen og \noppdaterer varelageret…',
    stock_count_has_been_finished: 'Varetelling er fullført',
    all_the_involved_inventory:
      'Alle involverte varelager har blitt \noppdatert. Vi har sent varetellingsrapporten \ntil ',
    something_went_wrong: 'Noe gikk galt',
    we_could_not_finish_the_stockcount:
      'Vi klarte ikke å avslutte varetellingen \nog oppdatere varelagrene. \nVennligst sjekk internettforbindelsen din \nog prøv igjen om litt.',
    clear_all_item: 'Fjern alle varer \nfra utsjekkslisten?',
    cancel_checkout_item: 'Avbrty utsjekking?',
    this_action_is: 'Det er ikke mulig å reversere denne handlingen',
    if_you_cancel_the_checkout:
      'Hvis du avbryter utsjekkingen vil alle varerene \ni utsjekkslisten bli fjernet.',
    yes_clear_all_item: 'Ja, fjern alle varene',
    yes_cancel_checkout: 'Ja, avbrty utsjekking',
    no_do_not_clear_them: 'Nei, ikke fjern varene',
    no_cancel_it: 'Nei, ikke avbryt',
    which_inventory_should_Update:
      'Hvilke varelager skal oppdateres når du \nmarkerer varene i denne leveransen som levert?',
    there_is_nothing_checkout: 'Det er ingen varer å sjekke ut.',
    remove_from_the_checkout_list: ' har blitt fjernet fra utsjekkslisten.',
    checkout_quantity_of: 'Checkout quantity of ',
    confirm_checkout: 'Bekreft utsjekking',
    are_you_sure_you_want_checkout:
      'Er du sikker på at du vil sjekke ut varer fra ',
    confirm_check_out: 'Bekreft utsjekking',
    go_back_to_checkout: 'Gå tilbake til utsjekkslisten',
    yes_cancel_transfer: 'Ja, avbryt overføringen',
    cancel_transfer_item: 'Avbryt overføring?',
    if_you_cancel_the_transfer:
      'Hvis du avbryter overføringen vil alle varene fjernes fra overføringslisten.',
    clear_all_item_Transfer: 'Fjern alle varene \nfra overføringslisten?',
    after_transfer: 'Etter overføring',
    after_checkout: 'Etter utsjekking',
    transfer_add_snack_text: 'har blitt lagt til i overføringslisten.',
    remove_from_the_transfer_list: ' har blitt fjernet fra overføringslisten.',
    update_text: 'har blitt oppdatert',
    transfer_update_text: 'Transfer quantity of',
    checkout_update_text: 'Checkout quantity of',
    checkout_add_snack_text: 'har blitt lagt til i utsjekkslisten.',
    remove_from_transfer_list: 'Fjern fra overføringslisten',
    remove_from_checkout_list: 'Fjern fra utsjekkslisten',
    total_to_transfer: 'Totalen til overføring',
    confirm_transfer: 'Bekreft overføring',
    are_you_sure_you_want_transfer: 'Er du sikker på at du ønsker å overføre ',
    items: 'varer',
    go_back_to_transfer: 'gå tilbake til overføringslisten',
    out_of: 'tom for',
    has_been_cancelled: 'har blitt avbrutt.',
    transfer_of_items_from: 'Overføring av varer fra',
    checkout_of_items_from: 'Utsjekking av varer fra',
    checkout_success_snack_text: 'varen har blitt sjekket ut fra',
    checkout_success_snack_second_text: 'varene har blitt sjekket ut fra',
    placeholder_text: 'f.eks 100,00',
    cost_per: 'Pris per',
    no_internet_connection_test: 'Ingen internettforbindelse',
    no_internet_connection_subtext: 'Vi kan ikke laste inn dataene dine.',
    retry_text: 'prøv igjen',
    you_can_edit: 'du kan redigere',
    you_can_view: 'du kan se',
    connection_lost: 'Tapt tilkobling',
    connection_lost_message:
      'Demo App-appens funksjonalitet kan være begrenset eller utilgjengelig til du er tilbake på nett.',
    no_internet_connection_popup_subtext:
      'Du er frakoblet. Vennligst sjekk tilkoblingen din og prøv igjen om noen øyeblikk.',
    add_item_to_an_inventory: 'Legg til vare i lageret',
    transfer_items_between_inventories: 'Overfør varer mellom lagre',
    no_inventories_edit: 'Ingen lagre\ndu kan redigere',
    no_inventories_view: 'Ingen lagre\ndu kan se',
    cost_summary: 'Kostnadsoversikt',
    cost_summary_sub_text:
      'Kostnadsoversikten gir omtrentlig totalverdi basert på de nyeste bestillingsprisene. Den endelige totale verdien i den ferdige varetellingsrapporten kan være litt annerledes fordi den tar hensyn til prisvariasjoner for varene på lageret.',
    show_zero: '0,00',
    approximate_total_value: 'Omtrentlig totalverdi',
    cost_summery_popup_text:
      'Den omtrentlige totale verdien av de telte varene er en estimat basert på de nyeste bestillingsprisene. Den endelige totale verdien i den ferdige varetellingsrapporten kan være litt annerledes fordi den tar hensyn til prisvariasjoner for varene på lageret.',
    reopen_stock_count: 'Gjenåpne varetelling',
    reopen_popup_title: 'Ønsker du å gjenåpne varetellingen?',
    reopen_popup_text:
      'Å gjenåpne en avsluttet varetelling lar deg gjøre endringer dersom du har oppdaget feil.',
    reopen_popup_text_second:
      'Ny varetellingsrapport vil automatisk bli generert når du fullfører varetellingen igjen.',
    reopen: 'Gjenåpne',
    stock_count_finish_in_the_process: 'Inventory count finish in the process',
    stock_count_finish_in_the_process_text:
      'your inventory count finish process is starting and we will inform you by the notification once the inventory count has been finished',
    bluetooth_allow_title_text: 'Demo App would like to use Bluetooth',
    bluetooth_allow_sub_text:
      'Demo App app needs Bluetooth to connect to the RFID scanner',
    allow: 'Allow',
    bluetooth_is_off: 'Bluetooth is off',
    bluetooth_is_off_sub_text:
      'Go to Settings and turn on Bluetooth to be able to connect your phone to the RFID scanner',
    open_settings: 'open settings',
    searching_for_RFID_scanner: 'Searching for RFID scanner',
    searching_for_RFID_scanner_sub_text:
      'Bring your phone closer to the RFID scanner, and ensure that the RFID scanner is turned on',
    connect: 'Connect',
    connecting: 'Connecting...',
    is_connected_to_your_phone: 'is connected to your phone',
    RFID_scanner: 'RFID scanner',
    scan_RFID: 'Scan RFID',
    gather_items_for_scanning_in_one: 'Gather items for scanning in one',
    place_Aim_your_RFID_scanner_at_them: 'place Aim your RFID scanner at them',
    press_the_scanner_button_to_see_the_items_and_their_quantities_here:
      'Press the scanner button to see the items and their quantities here',
    scanned_items: 'Scanned items',
    confirm_items: 'Confirm Items',
    add_a_new_item: 'Legg til ny vare til telte varer',
    signup_text: 'Ved å registrere deg godtar du',
    and: 'og',
    terms_of_use: 'Vilkår for bruk',
    privacy_policy: 'Personvernregler.',
    your_full_name: 'Ditt fulle navn',
    your_role: 'Din rolle',
    company_type: 'Bedriftstype',
    select_company_type: 'Velg firmatype...',
    country: 'Land',
    select_country: 'Velg land...',
    let_start: 'La oss begynne',
    eight_characters_minimum: '8 tegn minimum',
    please_fill_in_all_the_required_information:
      'Vennligst fyll inn all nødvendig informasjon',
    this_information_is_required: 'Denne informasjonen er påkrevd',
    please_select_an_option: 'Velg et alternativ',
    please_specify_company_type: 'Vennligst spesifiser firmatype...',
    inventory_count_made_easy: 'Varetelling gjort enkelt',
    welcome_message_text:
      'Demo App hjelper deg med å redusere tid brukt på varetelling og kutter matsvinnet ditt med opptil 35 %.',
    copyright_text: '© 2024 Demo App. Alle rettigheter forbeholdt.',
    password_error: 'Passord må være på minst 8 tegn',
    incorrect_email:
      'Feil e-postformat. Se etter et manglende "@" eller domene.',
    already_use_email_error:
      'Det ser ut til at det allerede er en konto med denne e-posten. Logg inn eller bruk en annen e-postadresse.',
    select_company_type_title: 'Velg Firmatype',
    select_country_title: 'Velg Land',
    one_step_closer: 'Et skritt nærmere!',
    initial_inventory_title_text:
      'Nå er det på tide å sette opp din første varebeholdning',
    initial_inventory_sub_text:
      'For å importere varebeholdningen din til Demo App, vennligst bytt til Demo App Admin-appen i nettleseren din på stasjonær eller bærbar PC.',
    initial_inventory_sub_text_second:
      'Vi har sendt deg en e-post med koblingen Demo App Admin og trinn du må følge.',
    there_nothing_inventory_sub_text:
      'For å enkelt laste opp alle varene dine, bytt til Demo App Admin-appen på en stasjonær eller bærbar datamaskin.',
    e_g_general_manager: 'f.eks. Daglig leder',
    please_fill_valid_total_product_cost: 'please fill valid total item cost',
    invalid_email: 'Ugyldig e-post',
    email_is_required: 'E-post kreves',
    ok: 'ok',
    verification_code_required: 'Verification code is required',
    invalid_verify_code: 'Invalid Verification Code',
  };
};
